# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_anchorpoints <- function(d, n_cubotti) {
    .Call('_LocallyStationaryModels_find_anchorpoints', PACKAGE = 'LocallyStationaryModels', d, n_cubotti)
}

variogramlsm <- function(z, d, anchorpoints, epsilon, n_angles, n_intervals, kernel_id, print, n_threads) {
    .Call('_LocallyStationaryModels_variogramlsm', PACKAGE = 'LocallyStationaryModels', z, d, anchorpoints, epsilon, n_angles, n_intervals, kernel_id, print, n_threads)
}

findsolutionslsm <- function(anchorpoints, empiricvariogram, squaredweights, mean_x, mean_y, variogram_id, kernel_id, parameters, lowerbound, upperbound, epsilon, print, n_threads) {
    .Call('_LocallyStationaryModels_findsolutionslsm', PACKAGE = 'LocallyStationaryModels', anchorpoints, empiricvariogram, squaredweights, mean_x, mean_y, variogram_id, kernel_id, parameters, lowerbound, upperbound, epsilon, print, n_threads)
}

predikt <- function(z, d, anchorpoints, epsilon, delta, solutions, positions, variogram_id, kernel_id, print, n_threads) {
    .Call('_LocallyStationaryModels_predikt', PACKAGE = 'LocallyStationaryModels', z, d, anchorpoints, epsilon, delta, solutions, positions, variogram_id, kernel_id, print, n_threads)
}

smoothing <- function(solutions, anchorpoints, delta, positions, kernel_id, n_threads) {
    .Call('_LocallyStationaryModels_smoothing', PACKAGE = 'LocallyStationaryModels', solutions, anchorpoints, delta, positions, kernel_id, n_threads)
}

