# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

variogramlsm <- function(y, d, anchorpoints, epsilon, n_angles, n_intervals, kernel_id) {
    .Call('_LocallyStationaryModels_variogramlsm', PACKAGE = 'LocallyStationaryModels', y, d, anchorpoints, epsilon, n_angles, n_intervals, kernel_id)
}

findsolutionslsm <- function(anchorpoints, empiricvariogram, squaredweights, x, y, variogram_id, parameters, epsilon) {
    .Call('_LocallyStationaryModels_findsolutionslsm', PACKAGE = 'LocallyStationaryModels', anchorpoints, empiricvariogram, squaredweights, x, y, variogram_id, parameters, epsilon)
}

fullmodel <- function(y, d, anchorpoints, parameters, epsilon, n_angles, n_intervals, kernel_id, variogram_id) {
    .Call('_LocallyStationaryModels_fullmodel', PACKAGE = 'LocallyStationaryModels', y, d, anchorpoints, parameters, epsilon, n_angles, n_intervals, kernel_id, variogram_id)
}

predikt <- function(y, d, anchorpoints, epsilon, delta, solutions, positions) {
    .Call('_LocallyStationaryModels_predikt', PACKAGE = 'LocallyStationaryModels', y, d, anchorpoints, epsilon, delta, solutions, positions)
}

find_anchorpoints <- function(d, n_cubotti) {
    .Call('_LocallyStationaryModels_find_anchorpoints', PACKAGE = 'LocallyStationaryModels', d, n_cubotti)
}

rawmodel <- function(y, d, anchorpoints, parameters, epsilon, n_angles, n_intervals, kernel_id, variogram_id) {
    .Call('_LocallyStationaryModels_rawmodel', PACKAGE = 'LocallyStationaryModels', y, d, anchorpoints, parameters, epsilon, n_angles, n_intervals, kernel_id, variogram_id)
}

fullmodelCV <- function(y, d, anchorpoints, parameters, epsilonmin, epsilonmax, nepsilons, n_angles, n_intervals, kernel_id, variogram_id) {
    .Call('_LocallyStationaryModels_fullmodelCV', PACKAGE = 'LocallyStationaryModels', y, d, anchorpoints, parameters, epsilonmin, epsilonmax, nepsilons, n_angles, n_intervals, kernel_id, variogram_id)
}

smoothing <- function(solutions, anchorpoints, delta, positions) {
    .Call('_LocallyStationaryModels_smoothing', PACKAGE = 'LocallyStationaryModels', solutions, anchorpoints, delta, positions)
}

buildgrid <- function(y, d, anchorpoints, epsilon, n_angles, n_intervals, kernel_id) {
    .Call('_LocallyStationaryModels_buildgrid', PACKAGE = 'LocallyStationaryModels', y, d, anchorpoints, epsilon, n_angles, n_intervals, kernel_id)
}

